stages:
- name: Publish Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test/pipeline-test:${CICD_GIT_TAG}
      pushRemote: true
      registry: so-nexus.delimanjoo.shop
    when:
      event:
        include:
        - push
        - tag
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    when:
      event:
        include:
        - push
        - tag
timeout: 60
notification:
  recipients:
  - recipient: rlathgml0102@gmail.com
    notifier: c-jnk2l:n-57xn9
  message: sohee_rancher pipeline start
  condition:
  - Success
  - Changed
  - Failed
