stages:
  # 이미지 생성
  - name: Publish Image
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile # Docker 이미지 생성 파일
          buildContext: .
          tag: test/pipeline-test:${CICD_GIT_TAG} # 참고 : https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/pipelines/#pipeline-variable-substitution-reference
          pushRemote: true # 선택옵션으로 외부 레지스트리에 Push 여부
          registry: so-nexus.delimanjoo.shop # 외부 레지스트리 주소
        when:
          event: tag # tag 이벤트 발생때 트리거
  # 배포
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./deployment.yaml # 배포 kubernetes YAML 파일
        when:
          event: tag # tag 이벤트 발생때 트리거
timeout: 60
triggerWebhookPr: true
triggerWebhookPush: true
triggerWebhookTag: true
branch:
  include:
  - master
  - develop

notification:
  recipients:
  - recipient: rlathgml0102@gmail.com
    notifier: c-jnk2l:n-57xn9
  message: sohee_rancher pipeline start
  condition:
  - Success
  - Changed
  - Failed
