stages:
- name: Publish Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ella1/front-page2:${CICD_GIT_TAG}
      pushRemote: true
      registry: nexus.bucketdata.io
  when:
    event:
      include:
      - push
      - pull_request
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
  when:
    branch:
      include:
      - master
    event:
      include:
      - push
timeout: 60
notification:
  recipients:
  - recipient: rlathgml0102@gmail.com
    notifier: c-jnk2l:n-57xn9
  message: sohee_rancher pipeline start
  condition:
  - Success
  - Changed
  - Failed
