stages:

- name: Publish Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ella1/front-page2:${CICD_GIT_TAG}
      pushRemote: true
      registry: nexus.delimanjoo.shop
#   env:
#     PLUGIN_BUILD_ARGS: "script=build-dev"
  when:
    event:
      include:
      - tag

- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
  when:
    branch: master
    event:
      include:
      - push

timeout: 60

notification:
  recipients:
  - recipient: rlathgml0102@gmail.com
    notifier: c-jnk2l:n-ftb78
  condition:
  - Failed
  - Success
  - Changed
  message: "sohee_rancher pipeline start"
