stages:
- name: Publish Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ella1/front-page2:${CICD_GIT_TAG}
      pushRemote: true
      registry: so-nexus.delimanjoo.shop
    when:
      branch: [ master, develop ]
      event:  [ tag ]


- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    when:
      branch: [ master, develop ]
      event:  [ tag ]

timeout: 60
triggerWebhookPr: true
triggerWebhookPush: true
triggerWebhookTag: true
branch:
  include:
  - master
  - develop

notification:
  recipients:
  - recipient: rlathgml0102@gmail.com
    notifier: c-jnk2l:n-57xn9
  message: sohee_rancher pipeline start
  condition:
  - Success
  - Changed
  - Failed
