apiVersion: v1
kind: Service
metadata:
  name: so-web
  namespace: so-app
spec:
  type: ClusterIP
  selector:
    app: so-web
  ports:
    - name: http
      port: 80
      protocol: TCP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: so-web
  namespace: so-app
spec:
  rules:
    - host: so-web.delimanjoo.shop
      http:
        paths:
          - backend:
              serviceName: so-web
              servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: so-web
  namespace: so-app
spec:
  replicas: 2
  minReadySeconds: 60
  progressDeadlineSeconds: 600
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: so-web
  template:
    metadata:
      labels:
        app: so-web
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - so-web
              topologyKey: kubernetes.io/hostname
      imagePullSecrets:
        - name: so-nexus
      containers:
        - name: so-web
          image: so-nexus.delimanjoo.shop/ella1/front-page2:0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 0.1Gi
            limits:
              memory: 0.1Gi
      restartPolicy: Always
