apiVersion: v1
kind: Service
metadata:
  name: onm-front
  namespace: sh-front-project
spec:
  type: ClusterIP
  selector:
    app: onm-front
  ports:
  - name: http
    port: 80
    protocol: TCP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sh-front
  namespace: app
spec:
  rules:
  - host: sohee.delimanjoo.shop
    http:
      paths:
      - backend:
          serviceName: sh-front
          servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sh-front
  namespace: app
spec:
  replicas: 2
  minReadySeconds: 60
  progressDeadlineSeconds: 600
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: sh-front
  template:
    metadata:
      labels:
        app: sh-front
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - onm-front
            topologyKey: kubernetes.io/hostname
      imagePullSecrets:
      - name: docker-ella
      containers:
      - name: sh-front
        image: nexus.delimanjoo.shop/ella1/front-page2:${CICD_GIT_TAG}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 0.1Gi
#            cpu: 1000m
          limits:
            memory: 0.1Gi
#            cpu: 1500m
      restartPolicy: Always
